name: PR

on:
  push:
    branches:
      - master
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: rust:1-bullseye
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
