name: PR

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: rust:1-bullseye
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
      - name: Setup grcov
        run: cargo install grcov
      - name: Build
        run: cargo build
        env:
          RUSTFLAGS: "-Cinstrument-coverage -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          RUSTC_BOOTSTRAP: "1"
          CARGO_INCREMENTAL: "0"
          RUSTDOCFLAGS: "-Cpanic=abort"
      - name: Test
        run: cargo test
        env:
          RUSTFLAGS: "-Cinstrument-coverage -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          RUSTC_BOOTSTRAP: "1"
          CARGO_INCREMENTAL: "0"
          RUSTDOCFLAGS: "-Cpanic=abort"
          LLVM_PROFILE_FILE: "your_name-%p-%m.profraw"
      - name: Generate coverage
        run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/debug/coverage/
        env:
          RUSTFLAGS: "-Cinstrument-coverage -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
          RUSTC_BOOTSTRAP: "1"
          CARGO_INCREMENTAL: "0"
          RUSTDOCFLAGS: "-Cpanic=abort"
          LLVM_PROFILE_FILE: "your_name-%p-%m.profraw"
      - uses: codecov/codecov-action@v3
